### ISSUE TITLE
Please add a license and a screen shot

### ISSUE THREAD

**Issue by unixorn** [logik93/rkj-logik.zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but the name `oh-my-zsh-theme` is awfully generic. Please consider renaming it to logik.zsh-theme to match the theme file

I also prefer to add themes with screen shots in their readme so that users can see what they look like without having to install them.

Finally, please add a license file, some people won't use any code that doesn't have a license. If you don't have one in mind, https://choosealicense.com is a good resource to help you select an appropriate one.

Thanks!

**Comment by logik93** [comment]
Fixed! :)
